language: objective-c

env:
 matrix:
  - MONO_VERSION="3.10.0"

before_install:
 # Make sure mono is installed
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
  - nuget restore src/Plankton.sln -source "https://www.nuget.org/api/v2;https://blooming-hollows-9801.herokuapp.com"
  - xbuild /p:Configuration=Release src/Plankton.sln
  - mono src/packages/NUnit.Runners.2.6.3/tools/nunit-console.exe bin/Release/PlanktonTests.dll
